### ISSUE TITLE
Documentation wishlist

### ISSUE THREAD

**Issue by broady** [NYTimes/marvin#10]
Better docs for:

- [x] ScalingHandler
- [x] RouterSelect and its semantics
- [x] Init: can be called from `main()`, too, not just `init()`
- [x] HTTPToFastRoute

Example for:

- [x] Internal middleware

**Comment by jprobinson** [comment]
I like the idea of using a main package in GAE so instead of just mentioning it in the docs, I was able to restructure the example to be a much closer match to how the gRPC/JSON server looks in gizmo/server/kit. The plan is to recreate the example over there with the cloud.google.com packages.

**Comment by jprobinson** [comment]
Howdy @broady. I'm not quite sure what you mean by "internal middleware". Are you looking for an example of using the `httptransport.ServerOption`s on the individual endpoints or something else?

**Comment by broady** [comment]
Oh, literally the `Internal` middleware:
http://godoc.org/github.com/NYTimes/marvin#Internal

`denial` has an `interface{}` type, which makes it non-obvious what to do with it. Apologies if this is me being a go-kit noob.

**Comment by broady** [comment]
> I like the idea of using a main package in GAE so instead of just mentioning it in the docs, I was able to restructure the example to be a much closer match to how the gRPC/JSON server looks in gizmo/server/kit. The plan is to recreate the example over there with the cloud.google.com packages.

Nice!

**Comment by jprobinson** [comment]
I've beefed up the docs for Internal in #15 so I'm going to close this issue for now. Feel free to reopen if you need more clarification.

In go-kit the `httptransport.DefaultErrorEncoder` is supplied that checks for `json.Marshaler`, `httptransport.Headerer` and `httptransport.StatusCoder`. The `marvin.JSONStatusResponse` implements all of those _and_ `error` so the folks can use it to wrap their business response structs and make the server respond appropriately.

I've added a new [defaultDenial](https://github.com/NYTimes/marvin/blob/master/middleware.go#L15-L17) that is used if none is supplied.

Time to bump the version!
