### ISSUE TITLE
marvintest encourages slow tests

### ISSUE THREAD

**Issue by broady** [NYTimes/marvin#9]
`SetupTestContextWithContext` is actually really slow - it starts up its own dev_appserver.

While that leads to relatively hermetic tests, it might be better to encourage people to use only one test context per package, rather than one per test or one per subtest.

**Comment by jprobinson** [comment]
This has been a pain for us internally (some test suites run longer than `npm install` 🙀!) but the convenience of the shutdown wiping the datastore in integration tests is almost too nice to pass up.

Do you have any recommended patterns for clearing the environment between test cases?

For packages that don't require integration tests with the dev_appserver, I'll definitely start looking to put the `SetupContextWithContext` in the `TestMain`. I'll see if I can squeeze in an example.

**Comment by broady** [comment]
Either manually (i.e, writing cleanup code -- watch out for Parallel tests!), or maybe more elegantly: using [namespaces](https://godoc.org/google.golang.org/appengine#Namespace).

Though the mechanism for namespaces is different in the [non-App Engine libraries](https://godoc.org/cloud.google.com/go/datastore#Key), since it's a bit of an abuse of `Context`.
